[[language]]
name = "go"
formatter = { command = "goimports", args = [] }

[[language]]
name = "haskell"
auto-format = true

[language-server.haskell-language-server]
config = {}

[language-server.yaml-language-server]
config = { yaml = { keyOrdering = false } }
